#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

export HOME=$OPENSHIFT_REPO_DIR/libs

cat $OPENSHIFT_REPO_DIR/libs/lists_list | python $OPENSHIFT_REPO_DIR/libs/mlstats \
--db-admin-user "$OPENSHIFT_DB_USERNAME" --db-admin-password "$OPENSHIFT_DB_PASSWORD" --no-report \
--db-hostname=$OPENSHIFT_DB_HOST --db-user "$OPENSHIFT_DB_USERNAME" --db-password "$OPENSHIFT_DB_PASSWORD" -

# queries here

sh $OPENSHIFT_REPO_DIR/libs/queries/lists.sh
