#!/bin/bash



# This home setting gives mlstats a place to put its .mlstats dir, where
# it put dl'ed files. There's probably a better place for these.

export HOME=$OPENSHIFT_REPO_DIR/libs

# this loads/updates the db with the list from the lists_list

cat $OPENSHIFT_REPO_DIR/libs/lists_list | python $OPENSHIFT_REPO_DIR/libs/mlstats \
--db-admin-user "$OPENSHIFT_DB_USERNAME" --db-admin-password "$OPENSHIFT_DB_PASSWORD" --no-report \
--db-hostname=$OPENSHIFT_DB_HOST --db-user "$OPENSHIFT_DB_USERNAME" --db-password "$OPENSHIFT_DB_PASSWORD" -

# Queries go here, comment, uncomment or add at will. These query scripts
# need only generate a csv file w/ data and generate an html file to show
# the data. The scripts lists.sh and domains.sh should work automatically
# with any lists pasted into /libs/lists_list. 


sh $OPENSHIFT_REPO_DIR/libs/queries/lists.sh
sh $OPENSHIFT_REPO_DIR/libs/queries/domains.sh

# create simple index page from all *.html pages in this dir not named index.html (the charts)

echo "<h1>mlstats-o-matic charts list:</h1><ul>" >> tmp
for i in `find *.html ! -type d ! -name 'index.html' | xargs ls`; do
 echo "<li><a href=\"$i\">$i</a>" >> tmp
done
echo "</ul>" >> tmp
mv tmp index.html
