#!/bin/bash

# this loads/updates the db with the list from the lists_list

export HOME=$OPENSHIFT_REPO_DIR/libs

cat $OPENSHIFT_REPO_DIR/libs/lists_list | python $OPENSHIFT_REPO_DIR/libs/mlstats \
--db-admin-user "$OPENSHIFT_DB_USERNAME" --db-admin-password "$OPENSHIFT_DB_PASSWORD" --no-report \
--db-hostname=$OPENSHIFT_DB_HOST --db-user "$OPENSHIFT_DB_USERNAME" --db-password "$OPENSHIFT_DB_PASSWORD" -

# queries here

sh $OPENSHIFT_REPO_DIR/libs/queries/lists.sh
